function gratingmat = mk_grating(varargin)
%MK_GRATING Converts a matrix using a sinusoidal function.
%
%   GRATINGMAT = MK_GRATING(PIXELMAP, FREQ [,PHASE]) returns a matrix with the
%   same size as PIXELMAP. Elements in the PIXELMAP are transformed using a
%   sinusoidal function with a frequency of FREQ, and the phase of the sinusoid
%   will be shifted by PHASE degrees. Output values are scaled to a range
%   between 0 and 1.
%
%   Arguments:
%      PIXELMAP - an image matrix, usually generated by MAP_* functions.
%      FREQ     - the frequency of a sinusoid in cycles per pixel.
%      PHASE    - the phase shift of a sinusoid, 90 if empty or not provided.
%
%   Example:
%      <a href="matlab:imshow(mk_grating(map_linear(200), 1 / 50));">imshow(mk_grating(map_linear(200), 1 / 50));</a>  % 1 cycle / 50 pixels
%
%   See also MAP_LINEAR, MAP_RADIAL.

	pixelmap = pretina_arg(varargin, 1, mfilename, 'pixelmap', [], {'numeric'}, {'nonempty', 'real', 'finite', 'nonnan'});
	freq     = pretina_arg(varargin, 2, mfilename, 'freq',     [], {'numeric'}, {'scalar', 'real', 'finite', 'nonnan'});
	phase    = pretina_arg(varargin, 3, mfilename, 'phase',    90, {'numeric'}, {'scalar', 'real', 'finite', 'nonnan'});

	gratingmat = sind(pixelmap * freq * 360 + phase) * .5 + .5;
end